version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfilebackend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfilefrontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
